name: Show Me the S3cr3tz
on: [push]

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up secret file
      # env:
      #   ENV_VAR: ${{ secrets.ENV_VAR }}
      # run: |
      #   echo $ENV_VAR | sed 's/./& /g'
      run: 'echo "$SSH_KEY" | base64'
      shell: bash
      env:
        SSH_KEY: ${{ secrets.ENV_VAR }}


    - name: Print secret
      env:
        ENV_VAR: ${{ secrets.ENV_VAR }}
      run: |
        echo ${{secrets.ENV_VAR}} | sed 's/./& /g'